version: '3.5'

networks:
  local:

services:
  openvswitch:
    container_name: openvswitch
    build:
      context: .
      dockerfile: openvswitch.docker
    volumes:
      - ./core:/app/mount
    privileged: true
    network_mode: host
  backend:
    container_name: ub_switch_api
    build:
      context: .
      dockerfile: ub_switch_api.docker
    restart: unless-stopped
    depends_on:
      - openvswitch
    expose:
      - 8081:5000

