version: '3.5'

services:
  openvswitch:
    container_name: ub_switch_api
    build:
      context: .
      dockerfile: openvswitch.docker
    volumes:
      - ./core:/app/mount
    privileged: true
    network_mode: host
    restart: unless-stopped

